### ISSUE TITLE
Type Error when using presetCatppuccin with UnoCSS

### ISSUE THREAD

**Issue by Be1my** [catuhana/unocss-catppuccin#107]
I am trying to use the `presetCatppuccin` with UnoCSS, but I am encountering the following TypeScript error:

`Type 'Preset<object>' is not assignable to type 'PresetOrFactory<any> | PresetOrFactory<any>[]'.
  Type 'Preset<object>' is not assignable to type 'Preset<any>'.
    Types of property 'rules' are incompatible.
      Type 'Rule<object>[]' is not assignable to type 'Rule<any>[]'.
        Type 'Rule<object>' is not assignable to type 'Rule<any>'.
          Type 'DynamicRule<object>' is not assignable to type 'Rule<any>'.
            Type '[RegExp, DynamicMatcher<object>, RuleMeta?]' is not assignable to type 'StaticRule'.
              Type at position 0 in source is not compatible with type at position 0 in target.
                Type 'RegExp' is not assignable to type 'string'.`

This issue started occurring recently after I updated my project, but everything was working fine a year ago when I last used this package. Although the project runs without issues, the TypeScript error is quite annoying.

**Comment by catuhana** [comment]
It seems like UnoCSS has updated some internal things? I'll fix this ASAP. In the meantime, you can use the UnoCSS version used by this library, which should be recent enough

**Comment by catuhana** [comment]
It seems like it was already fixed with https://github.com/catuhana/unocss-catppuccin/commit/03d530ea4b8d051526b2e5f76f2900ce3e439910, as I have no issues with local source. Will release v1.1.2 soon after bumping dependencies.

**Comment by catuhana** [comment]
v1.1.2 should be available in npm and JSR soon. Please let me know if it's not fixed or there are other issues.

**Comment by Be1my** [comment]
Thank you for the update! I've tried v1.1.3, but the issue still seems to persist.

**Comment by catuhana** [comment]
> Thank you for the update! I've tried v1.1.3, but the issue still seems to persist.

That seems weird, I can't reproduce it myself. Can you create a simple repository to reproduce, so I can test things?

**Comment by Be1my** [comment]
It seems to be a version issue in the package.json. The error disappeared when I updated unocss to v0.64.0.
https://github.com/unocss/unocss/issues/1227#issuecomment-1175920858

**Comment by catuhana** [comment]
Ah, that makes sense. This issue (installed UnoCSS and library UnoCSS version not matching) would be warned about with #106 by the package managers itself.
